---
abstract: 'Simple quiz API'
author:
  - 'Ashley Pope <irashp@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200014, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Simple-Quiz
requires:
  Data::Dumper: 0
  Modern::Perl: 0
  Moose: 0
  POSIX: 0
  String::Approx: 0
  YAML::XS: 0
resources: {}
version: 0.001
